products/urls.py
from django.urls import path
from .views import read_products, create_products, update_products, delete_products

urlpatterns = [
    path('', read_products, name='read_products'),
    path('create', create_products, name='create_products'),
    path('upadate/<int:id>/', update_products, name='update_products'),
    path('delete/<int:id>/', delete_products, name='delete_products'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls'))
]

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.IntegerField()

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'quantity']

products/views.py
from itertools import product
from math import prod
from django.shortcuts import render, redirect
from django.core.handlers.wsgi import WSGIRequest
from .models import Product
from .forms import ProductForm

# Create your views here.
def read_products(request: WSGIRequest):
    products = Product.objects.all()
    return render(
            request,
            'products.html',
            {'products': products},
        )


def create_products(request: WSGIRequest):
    form = ProductForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('read_products')
    
    return render(request, 'products-form.html', {'form': form})


def update_products(request: WSGIRequest, id: int):
    product = Product.objects.get(id=id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid():
        form.save()
        return redirect('read_products')
    
    return render(request, 'products-form.html', {'product': product})


def delete_products(request: WSGIRequest, id: int):
    product = Product.objects.get(id=id)
    
    if request.method == 'POST':
        product.delete()
        return redirect('read_products')
    
    return render(request, 'prod-delete-confirm.html', {'product': product})

products/views/views.py
from itertools import product
from math import prod
from django.shortcuts import render, redirect
from django.core.handlers.wsgi import WSGIRequest
from ..models import Product
from ..forms import ProductForm

# Create your views here.
def read_products(request: WSGIRequest):

    render_lambda = lambda products: render(request, 'products.html', {'products':products})

    search_param = request.GET.get('search', None)

    if search_param:
        products = Product.objects.filter(name__contains=search_param)
    else:
        products = Product.objects.all()
    
    return render_lambda(products)


def create_products(request: WSGIRequest):
    form = ProductForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('read_products')
    
    return render(request, 'products-form.html', {'form': form})


def update_products(request: WSGIRequest, id: int):
    product = Product.objects.get(id=id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid():
        form.save()
        return redirect('read_products')
    
    return render(request, 'products-form.html', {'product': product})


def delete_products(request: WSGIRequest, id: int):
    product = Product.objects.get(id=id)
    
    if request.method == 'POST':
        product.delete()
        return redirect('read_products')
    
    return render(request, 'prod-delete-confirm.html', {'product': product})

products/templates/prod-delete-confirm.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }
    </style>
    <title>Deleção de Item</title>
</head>
<body>
    <form class="mt-3" method="post" style="max-width:800px; width: 100%">
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            Tem certeza que deseja remover o produto: {{ product.name }} ?
        </div>
        <button
            class="btn btn-danger mt-2"
            type="submit"
            style="width: 100%;max-width: 800px;"
        >
            Deletar
        </button>
    </form>
    <a
            class="btn btn-outline-dark mt-2"
            href="{% url 'read_products' %}"
            style="width: 100%;max-width: 800px;"
        >
            Cancelar
    </a>
     <!-- SCRIPTS DE ESTILO DO BOOTSTRAP-->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

products/templates/products-form.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        h1 {
            text-align: center;
        }

        .formRoot {
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .formInput {
            display: flex;
            flex-direction: row;
            width: 100%;
            max-width: 800px;
            align-items: center;
            justify-content: space-between;
        }

        .formInput > input {
            margin: auto;
            width: 49%;
        }

        body {
            text-align: center;
        }
    </style>
    <title>Criação e Atualização de Documentos</title>
</head>
<body>
    {% if product %}
        <h1>Atualizar Produtor</h1>
    {% else %}
        <h1>Criar Produto</h1>
    {% endif %}
    <form method="post" class="mt-3 formRoot">
        {% csrf_token %}
        <!-- {{ form }} -->
        <div class="form-group formInput">
            <input
                placeholder="Nome"
                type="text"
                name="name"
                maxlength="50"
                id="id_name"
                value='{{product.name}}'
                class="form-control mb-1"
                required
            />
            <input
                placeholder="Descrição"
                type="text"
                name="description"
                maxlength="200"
                id="id_description"
                value="{{ product.description }}"
                class="form-control mb-1"
                required
            />
        </div>
        <div class="form-group formInput">
            <input
                placeholder="Preço"
                type="number"
                step="0.01"
                name="price"
                maxlength="50"
                id="id_price"
                value="{{ product.price }}"
                class="form-control mb-1"
                required
            />
            <input
                placeholder="Quantidade"
                type="number"
                name="quantity"
                maxlength="50"
                id="id_price"
                value="{{ product.quantity }}"
                class="form-control mb-1"
                required
            />
        </div>
        <button
            type="submit"
            class="btn btn-primary mt-2"
            style="width: 100%;max-width: 800px;"
        >
            Salvar
        </button>
    </form>
        <a
            class="btn btn-outline-dark mt-2"
            href="{% url 'read_products' %}"
            style="width: 100%;max-width: 800px;"
        >
            Cancelar
        </a>
    {% if product %}
        <a
            class="btn btn-danger mt-2"
            href="{% url 'delete_products' product.id %}"
            style="width: 100%;max-width: 800px;"
        >
            Deletar
        </a>
    {% endif %}
    
    <!-- SCRIPTS DE ESTILO DO BOOTSTRAP-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

products/templates/products.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .table-root {
            display: flex;
            flex-direction: column;
            width: 100%;
            align-items: center;
            justify-content: center;
            margin-top: 24px;
        }

        .create-container {
            display: flex;
            width: 100%;
            align-items: center;
            justify-content: center;
        }

        .root-input-group {
            padding: 16px;
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
        }

        .contentAll {
            width: 100%;
            max-width: 900px;
        }

        .search_input:hover {
            cursor: pointer;
            background-color: #919191;
            color: white;
            user-select: none;
        }
    </style>
    <title>Produtos</title>
</head>
<body>
    <div class="root-input-group">
        <form method="GET" class="input-group contentAll">
            <input
                type="text"
                placeholder="Pesquisar"
                name="search"
                class="form-control"
            />
            <button type="submit" class="input-group-text search_input" id="inputGroup-sizing-sm">Pesquisar</button>
        </form>
    </div>
    <div class="table-root">
        <table class="table table-striped table-hover align-middle contentAll">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Preço</th>
                    <th>Quantidade</th>
                    <th>Editar</th>
                    <th>Deletar</th>
                </tr>
            </thead>
            <tbody>
                {% if not products %}
                    <tr class="alert alert-info" role="alert">
                        <td colspan="6"> A busca não retornou nenhum dado</td>
                    </tr>
                {% endif %}
                {% for product in products %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <td>{{ product.description }}</td>
                        <td>{{ product.price }}</td>
                        <td>{{ product.quantity }}</td>
                        <td>
                            <a href="{% url 'update_products' product.id %}" class="btn btn-primary">Editar</a>
                        </td>
                        <td>
                            <a href="{% url 'delete_products' product.id %}" class="btn btn-danger">Deletar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="create-container">
        <a href="{% url 'create_products'%}" class="btn btn-outline-dark">Criar Produto</a>
    </div>
    <!-- SCRIPTS DE ESTILO DO BOOTSTRAP-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>